version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - ls -l 
      - pwd
      - ls
      - python manage.py collectstatic --no-input
      - python manage.py migrate
      - zip -r parking.zip . -x "*.git*" "*__pycache__*" "*.pyc" "*.pyo" "env/*"
artifacts:
  files:
    - "**/*"
  discard-paths: no
