version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install -r requirements.txt
  pre_build:
    commands:
      - echo "Running Pylint..."
      # Run Pylint and capture the rating in a variable
      - |
        # Run Pylint and extract the score
        PYTHON_FILES=$(find . -name "*.py")
        echo "Analyzing Python files: $PYTHON_FILES"

        pylint $PYTHON_FILES --exit-zero > pylint_report.txt

        # Extract the Pylint score robustly
        SCORE=$(pylint $PYTHON_FILES --exit-zero | grep -Eo 'Your code has been rated at [0-9]+\.[0-9]+' | grep -Eo '[0-9]+\.[0-9]+')

        echo "Pylint Score: $SCORE"

        # Set the threshold and fail if the score is below it
        THRESHOLD=3.0
        if (( $(echo "$SCORE < $THRESHOLD" | bc -l) )); then
          echo "Pylint score $SCORE is below threshold $THRESHOLD. Failing the build."
          exit 1
        else
          echo "Pylint score $SCORE meets the threshold $THRESHOLD. Build passed."
        fi



  build:
    commands:
      - ls -l 
      - pwd
      - ls
      - python manage.py collectstatic --no-input
      - python manage.py migrate
      - zip -r parking.zip . -x "*.git*" "*__pycache__*" "*.pyc" "*.pyo" "env/*"
artifacts:
  files:
    - "**/*"
  discard-paths: no


 

# version: 0.2

# env:
#   secrets-manager:
#     LOGIN: arn:aws:secretsmanager:eu-west-1:250738637992:secret:x23249463-lyuble-car-parking-maPJoU:sonartoken     # SonarQube token
#     HOST: arn:aws:secretsmanager:eu-west-1:250738637992:secret:x23249463-lyuble-car-parking-maPJoU:HOST           # SonarQube server URL
#     Organization: arn:aws:secretsmanager:eu-west-1:250738637992:secret:x23249463-lyuble-car-parking-maPJoU:Organization  # Organization name in SonarQube
#     Project: arn:aws:secretsmanager:eu-west-1:250738637992:secret:x23249463-lyuble-car-parking-maPJoU:Project     # Project key in SonarQube

# phases:
#   install:
#     runtime-versions:
#       python: 3.11
#     commands:
#       - yum install -y jq
#       - echo "Installing dependencies..."
#       - pip install -r requirements.txt
#       - echo "Installing SonarQube Scanner..."
#       - wget -O sonar-scanner-cli.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
#       - unzip sonar-scanner-cli.zip
#       - export PATH=$PATH:$(pwd)/sonar-scanner-5.0.1.3006-linux/bin


#   build:
#     commands:
#       # Fetch Quality Gate status
#       - echo "Checking SonarQube Quality Gate status..."
#       - |
#         SONAR_STATUS=$(curl -s -u $LOGIN: "$HOST/api/qualitygates/project_status?projectKey=$Project" | jq -r '.projectStatus.status')
#         echo "Quality Gate status: $SONAR_STATUS"
#         if [ "$SONAR_STATUS" != "OK" ]; then
#           echo "Quality Gate FAILED. Exiting pipeline."
#           exit 1
#         else
#           echo "Quality Gate PASSED."
#         fi


#       - echo "Running Django commands..."
#       - python manage.py collectstatic --no-input
#       - python manage.py migrate
#       - echo "Zipping project for deployment..."
#       - zip -r parking.zip . -x "*.git*" "*__pycache__*" "*.pyc" "*.pyo" "env/*"

# artifacts:
#   files:
#     - "**/*"
#   discard-paths: no




