version: 0.2
env:
  secrets-manager:
    LOGIN: prod/sonar:sonartoken
    HOST: prod/sonar:HOST
    Organization: prod/sonar:Organization
    Project: prod/sonar:Project
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - ls -l 
      - pwd
      - ls
      - python manage.py collectstatic --no-input
      - python manage.py migrate
      - zip -r parking.zip . -x "*.git*" "*__pycache__*" "*.pyc" "*.pyo" "env/*"
artifacts:
  files:
    - "**/*"
  discard-paths: no
